import{describe,expect,it}from'vitest';import{lintItem}from'./item-lint.js';
const item={stem:'Qual é a conduta inicial mais adequada para este paciente?',correct:'A' as const,alternatives:[{id:'A' as const,text:'Administrar cálcio intravenoso.'},{id:'B' as const,text:'Administrar expansão volêmica.'},{id:'C' as const,text:'Solicitar radiografia simples.'},{id:'D' as const,text:'Prescrever diurético oral.'}]};
describe('lint determinístico do item',()=>{
 it('não bloqueia linguagem clínica probabilística',()=>{const result=lintItem({...item,stem:'Qual diagnóstico pode explicar melhor este quadro?'});expect(result.repair_issues).toEqual([]);expect(result.warnings).toHaveLength(1)});
 it('detecta enunciado negativo',()=>expect(lintItem({...item,stem:'Qual das alternativas NÃO é adequada?'}).repair_issues[0]).toContain('negativo'));
 it('detecta todas as anteriores',()=>expect(lintItem({...item,alternatives:[...item.alternatives.slice(0,3),{id:'D',text:'Todas as anteriores.'}]}).repair_issues).toHaveLength(1));
 it('detecta correta desproporcional',()=>expect(lintItem({...item,alternatives:[{id:'A',text:'Administrar imediatamente gluconato de cálcio intravenoso com monitorização eletrocardiográfica contínua durante todo o procedimento.'},...item.alternatives.slice(1)]}).repair_issues).toContain('A alternativa correta é muito mais longa que os distratores e cria pista visual.'));
 it('detecta correta escolhível por reunir mais ações',()=>expect(lintItem({...item,alternatives:[{id:'A',text:'Iniciar magnésio, controlar a pressão e indicar o parto.'},{id:'B',text:'Manter vigilância e aguardar o termo.'},{id:'C',text:'Realizar cesariana após estabilização.'},{id:'D',text:'Prescrever anti-hipertensivo e observar.'}]}).repair_issues).toContain('A alternativa correta reúne mais ações que todos os distratores e pode ser escolhida por completude formal.'));
});
