import { assertBudget,recordEstimatedCost } from './budget.js';
import { blueprintSchema,generatedQuestionSchema,reviewSchema } from './schema.js';
import { providers,type ModelProvider,type ProviderResult } from './providers.js';
import { benchmarkAgainstEnamed2025 } from './enamed-benchmark.js';
import { rubricIssues } from './review-gate.js';
const json=(text:string)=>JSON.parse(text.replace(/^```json\s*/,'').replace(/```\s*$/,''));
const cost=(r:ProviderResult)=>recordEstimatedCost(r.usage.provider,r.usage.inputTokens,r.usage.outputTokens);
type Provenance={step:string;cycle:number;provider:string;model:string;cost:number};
type Pair={generator:ModelProvider;reviewer:ModelProvider};

export async function runPipeline(input:unknown,pair:Pair=providers()){
 assertBudget();const blueprint=blueprintSchema.parse(input);const maxCycles=Math.max(0,Math.min(3,Number(process.env.AI_MAX_REPAIR_CYCLES||2)));const provenance:Provenance[]=[];
 const generated=await pair.generator.generate('Construa uma questão inédita de treino médico. Responda apenas JSON válido, com quatro alternativas ABCD e uma correta. Não alegue revisão humana nem fonte verificada. Se não recordar uma referência identificável, não invente dados bibliográficos.',`Blueprint: ${JSON.stringify(blueprint)}. Produza area, topic, stem, alternatives[{id,text,rationale}], correct, pearl, source, source_claim e source_evidence{title,issuer,year,locator,excerpt,url opcional}. O excerpt deve ser curto e sustentar diretamente source_claim; locator deve permitir conferência humana.`);provenance.push({step:'generate',cycle:0,provider:generated.usage.provider,model:generated.usage.model,cost:cost(generated)});let question=generatedQuestionSchema.parse(json(generated.text));
 for(let cycle=0;cycle<=maxCycles;cycle++){
  assertBudget();const blinded={...question,correct:undefined,pearl:undefined,alternatives:question.alternatives.map(({rationale,...a})=>a)};const reviewed=await pair.reviewer.generate('Atue como elaborador experiente de avaliação clínica. Resolva às cegas e critique sem confiar no gabarito do autor. Responda somente JSON.',`Questão cega: ${JSON.stringify(blinded)}. Produza chosen_answer (A/B/C/D/NONE/AMBIGUOUS), safe, rubric com decision_focus, data_sufficiency, distractor_plausibility, cue_absence e clinical_safety; cada dimensão deve ter score inteiro 0 (falha grave), 1 (requer reparo) ou 2 (atende integralmente) e evidence concreta. Produza também blocking_issues[], quality_issues[], source_needs_check e recommendation (approve/repair/block). Não dê score 2 sem apontar evidência observável no item.`);provenance.push({step:'blind_review',cycle,provider:reviewed.usage.provider,model:reviewed.usage.model,cost:cost(reviewed)});const review=reviewSchema.parse(json(reviewed.text));const agrees=review.chosen_answer===question.correct;const benchmark=benchmarkAgainstEnamed2025(question);const qualitativeIssues=rubricIssues(review);const formatPasses=benchmark.issues.length===0;const qualityPasses=qualitativeIssues.length===0;
  if(review.safe&&agrees&&review.recommendation==='approve'&&formatPasses&&qualityPasses)return{question,status:'auto_verified',review,benchmark,qualitative_issues:qualitativeIssues,cycles:cycle,source_status:'unverified',provenance,disclaimer:'Verificação automática não equivale a revisão por especialista. A fonte ainda precisa de confirmação documental.'};
  if(review.recommendation==='block'||!review.safe||cycle===maxCycles)return{question,status:'blocked',review,benchmark,cycles:cycle,source_status:'unverified',provenance,disclaimer:'Questão bloqueada; não pode ser publicada ao estudante.'};
  assertBudget();const repaired=await pair.generator.generate('Reconstrua a questão corrigindo somente problemas demonstrados. Produza JSON completo no mesmo schema. Não alegue revisão humana ou fonte verificada.',`Blueprint: ${JSON.stringify(blueprint)}\nQuestão atual: ${JSON.stringify(question)}\nRevisão cega: ${JSON.stringify(review)}\nProblemas da régua qualitativa: ${JSON.stringify(qualitativeIssues)}\nBenchmark estrutural: ${JSON.stringify(benchmark)}\nA resposta do revisor concorda com o gabarito? ${agrees}. Corrija ambiguidades, mérito ou qualidade e devolva o item completo.`);provenance.push({step:'repair',cycle:cycle+1,provider:repaired.usage.provider,model:repaired.usage.model,cost:cost(repaired)});question=generatedQuestionSchema.parse(json(repaired.text));
 }
 throw new Error('Estado inalcançável do pipeline');
}
