import { useEffect, useState } from 'react';
import { Activity, CircleAlert, CircleDollarSign, Gauge, LoaderCircle, ShieldCheck, Users } from 'lucide-react';
import type { ReactNode } from 'react';
import { supabase, useAuth } from './auth';
import type { Attempt } from './types';

type Summary={students:number;attempts:number;active7:number;active30:number;correct_rate:number;high_confidence_errors:number;avg_response_ms:number;ai_cost_usd:number};
type Student={id:string;name:string;phase:number|null;attempts:number;correct_rate:number;high_confidence_errors:number;last_activity:string|null};
type Dashboard={summary:Summary;students:Student[]};

export function AdminDashboard({attempts}:{attempts:Attempt[]}){
 const {user}=useAuth();const [data,setData]=useState<Dashboard|null>(null);const [loading,setLoading]=useState(user?.mode==='supabase');const [error,setError]=useState('');
 useEffect(()=>{if(user?.mode!=='supabase'||!supabase){setLoading(false);return}let active=true;supabase.rpc('admin_dashboard').then(({data,error})=>{if(!active)return;if(error)setError(error.message);else setData(data as Dashboard);setLoading(false)});return()=>{active=false}},[user?.id,user?.mode]);
 if(loading)return <section className="panel adminState"><LoaderCircle className="spin"/><p>Calculando indicadores protegidos…</p></section>;
 if(error)return <section className="panel adminState adminFailure"><CircleAlert/><h2>Não foi possível abrir o painel</h2><p>{error}</p></section>;
 if(user?.mode==='demo'||!data)return <DemoDashboard attempts={attempts}/>;
 const s=data.summary;return <><header><div><p className="eyebrow">ADMINISTRAÇÃO · DADOS REAIS</p><h1>Funcionamento e desempenho formativo</h1><p>A identificação nominal abaixo é restrita ao administrador e deve ser usada apenas para acompanhamento educacional legítimo.</p></div><span className="status especialista">Acesso restrito</span></header><div className="adminMetrics"><AdminMetric icon={<Users/>} label="Estudantes" value={String(s.students)} note={`${s.active7} ativos em 7 dias`}/><AdminMetric icon={<Activity/>} label="Respostas" value={String(s.attempts)} note={`${s.active30} ativos em 30 dias`}/><AdminMetric icon={<Gauge/>} label="Precisão global" value={`${s.correct_rate}%`} note={`${s.high_confidence_errors} erros com alta confiança`}/><AdminMetric icon={<CircleDollarSign/>} label="Custo estimado de IA" value={`US$ ${Number(s.ai_cost_usd).toFixed(2)}`} note={`${Math.round(s.avg_response_ms/1000)}s de resposta média`}/></div><section className="panel"><div className="sectionTitle"><div><p className="eyebrow">ACOMPANHAMENTO</p><h2>Desempenho por estudante</h2></div><ShieldCheck/></div><div className="studentTable"><div className="studentHead"><span>Estudante</span><span>Fase</span><span>Respostas</span><span>Precisão</span><span>Alertas</span><span>Última atividade</span></div>{data.students.map(student=><div key={student.id}><b>{student.name}</b><span>{student.phase||'—'}</span><span>{student.attempts}</span><span>{student.correct_rate}%</span><span>{student.high_confidence_errors}</span><span>{student.last_activity?new Date(student.last_activity).toLocaleDateString('pt-BR'):'Nunca'}</span></div>)}</div><p className="privacyFootnote">Minimização aplicada: o painel não exibe e-mail, alternativa escolhida ou texto livre do estudante.</p></section></>;
}

function DemoDashboard({attempts}:{attempts:Attempt[]}){const correct=attempts.filter(a=>a.correct).length;const highWrong=attempts.filter(a=>!a.correct&&a.confidence===3).length;return <><header><div><p className="eyebrow">ADMINISTRAÇÃO · MODO DEMONSTRATIVO</p><h1>Visão de funcionamento e desempenho</h1><p>Os indicadores usam somente tentativas deste navegador.</p></div><span className="status experimental">Dados locais</span></header><div className="adminMetrics"><AdminMetric icon={<Users/>} label="Usuários cadastrados" value="1" note="perfil demonstrativo"/><AdminMetric icon={<Activity/>} label="Respostas registradas" value={String(attempts.length)} note={`${correct} corretas`}/><AdminMetric icon={<CircleAlert/>} label="Erros com alta confiança" value={String(highWrong)} note="prioridade formativa"/><AdminMetric icon={<CircleDollarSign/>} label="Custo de IA" value="US$ 0,00" note="sem banco conectado"/></div></>}
function AdminMetric({icon,label,value,note}:{icon:ReactNode;label:string;value:string;note:string}){return <div className="adminMetric"><span>{icon}</span><small>{label}</small><b>{value}</b><p>{note}</p></div>}
