import { useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { BookOpenCheck, Brain, ChartNoAxesColumnIncreasing, ChevronRight, CircleAlert, ClipboardCheck, FlaskConical, Home, Library, LogOut, RotateCcw, ShieldCheck, Sparkles } from 'lucide-react';
import type { Alternative, Attempt, Question } from './types';
import { useAttempts } from './useAttempts';
import { useQuestionBank } from './useQuestionBank';
import { useAuth } from './auth';
import { Login } from './Login';
import { AdminDashboard } from './AdminDashboard';
import { StudioPanel } from './StudioPanel';
import { EditorialQueue } from './EditorialQueue';

type Page='home'|'train'|'review'|'progress'|'studio'|'editorial'|'admin'|'about'|'privacy'|'ai';
const labels={especialista:'Revisada por especialista',verificada_ia:'Verificada automaticamente',experimental:'Experimental'} as const;
const nav=[['home','Início',Home],['train','Treinar',Brain],['review','Revisar',RotateCcw],['progress','Progresso',ChartNoAxesColumnIncreasing]] as const;

export function App(){
 const [page,setPage]=useState<Page>('home'); const {user,loading,signOut}=useAuth(); const {attempts,add,persistenceError}=useAttempts(user); const {questions:bank,loading:bankLoading,error:bankError}=useQuestionBank(user);
 const [accepted,setAccepted]=useState(()=>localStorage.getItem('treino-consent-v1')==='accepted');
 if(!accepted)return <Consent onAccept={()=>{localStorage.setItem('treino-consent-v1','accepted');setAccepted(true)}}/>;
 if(loading)return <div className="loginPage">Verificando acesso…</div>;
 if(!user)return <Login/>;
 const editor=user.role==='reviewer'||user.role==='admin';
 return <div className="shell"><aside><div className="brand"><span>T</span><div>Treino <b>ENAMED</b><small>{user.mode==='demo'?'modo demonstrativo':'acesso protegido'}</small></div></div><nav>{nav.map(([id,label,Icon])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><Icon size={19}/>{label}</button>)}{editor&&<><button className={page==='studio'?'active':''} onClick={()=>setPage('studio')}><FlaskConical size={19}/>Estúdio</button><button className={page==='editorial'?'active':''} onClick={()=>setPage('editorial')}><ClipboardCheck size={19}/>Fila editorial</button></>}{user.role==='admin'&&<button className={page==='admin'?'active':''} onClick={()=>setPage('admin')}><ShieldCheck size={19}/>Administração</button>}<button onClick={()=>signOut()}><LogOut size={19}/>Sair</button></nav><div className="independent"><CircleAlert size={18}/><span>{user.name} · {user.role}<br/>Ferramenta independente e não oficial.</span></div></aside><main>{page==='home'&&<HomePage attempts={attempts} go={setPage}/>} {page==='train'&&<Training add={add} questions={bank} loading={bankLoading} error={bankError} persistenceError={persistenceError}/>}  {page==='review'&&<Review attempts={attempts} questions={bank}/>}  {page==='progress'&&<Progress attempts={attempts}/>} {page==='studio'&&editor&&<StudioPanel/>}{page==='editorial'&&editor&&<EditorialQueue/>}{page==='admin'&&user.role==='admin'&&<AdminDashboard attempts={attempts}/>} {page==='about'&&<About/>}{page==='privacy'&&<Privacy/>}{page==='ai'&&<AIUse/>}<Footer go={setPage}/></main></div>
}

function Consent({onAccept}:{onAccept:()=>void}){const [terms,setTerms]=useState(false);const [ai,setAi]=useState(false);return <div className="consentPage"><div className="consentCard"><div className="brand dark"><span>T</span><div>Treino <b>ENAMED</b><small>protótipo independente</small></div></div><p className="eyebrow">ANTES DE COMEÇAR</p><h1>Treino transparente, dados protegidos.</h1><p>Esta ferramenta é independente e seus resultados são exclusivamente formativos. Questões podem ter sido produzidas com assistência de inteligência artificial.</p><label><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>Li e concordo com os Termos de Uso e com o tratamento necessário dos meus dados para funcionamento do aplicativo.</span></label><label><input type="checkbox" checked={ai} onChange={e=>setAi(e.target.checked)}/><span>Compreendo que a IA pode cometer erros e que questões sem revisão humana serão identificadas.</span></label><button className="primary full" disabled={!terms||!ai} onClick={onAccept}>Entrar no protótipo <ChevronRight size={18}/></button><small className="draftWarning">Minutas para prototipação. Revisão jurídica obrigatória antes de uso público.</small></div></div>}

function LegalPage({kicker,title,children}:{kicker:string;title:string;children:ReactNode}){return <><header><div><p className="eyebrow">{kicker}</p><h1>{title}</h1></div></header><article className="legal">{children}<div className="notice"><CircleAlert/><p>Este texto é uma minuta funcional e deverá passar por revisão jurídica antes da disponibilização pública.</p></div></article></>}
function About(){return <LegalPage kicker="SOBRE" title="Treino independente, com limites explícitos"><h2>O que é</h2><p>Uma ferramenta independente de treino formativo para estudantes de Medicina, orientada à matriz do ENAMED.</p><h2>O que não é</h2><ul><li>Não é produto oficial do INEP ou MEC e não possui vínculo institucional.</li><li>Não substitui professores, diretrizes clínicas ou fontes primárias.</li><li>Não certifica, atribui nota acadêmica ou garante desempenho no exame.</li><li>Não oferece orientação para atendimento de pacientes reais.</li></ul><h2>Como funciona</h2><p>O aplicativo combina prática por questões, confiança, caderno de erros e revisão. A origem e o estado editorial de cada item são informados.</p><h2>Versão</h2><p>Protótipo funcional 0.1 · contato do responsável a definir.</p></LegalPage>}
function Privacy(){return <LegalPage kicker="PRIVACIDADE E LGPD" title="Seus dados devem servir ao seu estudo"><h2>Dados utilizados</h2><p>No protótipo atual, tentativas, respostas e confiança ficam apenas neste navegador. Quando houver login, poderão ser tratados nome, e-mail, fase, sessões, respostas, confiança, tempo e revisões.</p><h2>Finalidades</h2><ul><li>Manter a conta e a sessão.</li><li>Personalizar treino e revisão.</li><li>Exibir o progresso individual.</li><li>Produzir indicadores de funcionamento e qualidade.</li></ul><h2>Seus direitos</h2><p>O usuário poderá solicitar acesso, correção, exportação e exclusão. O canal e o responsável pelo tratamento serão definidos antes do piloto.</p><h2>Pesquisa é separada</h2><p>O uso do aplicativo não autoriza automaticamente utilização dos dados em pesquisa.</p></LegalPage>}
function AIUse(){return <LegalPage kicker="TRANSPARÊNCIA" title="Como usamos inteligência artificial"><p>IA poderá auxiliar na geração, classificação e verificação de questões. Esses sistemas podem produzir erros, referências inadequadas ou interpretações incorretas.</p><h2>Estados editoriais</h2><ul><li><b>Revisada por especialista:</b> revisão humana confirmada.</li><li><b>Verificada automaticamente:</b> passou por gates automáticos, sem revisão humana.</li><li><b>Experimental:</b> verificações ainda incompletas.</li></ul><h2>O que a IA não decide</h2><p>A IA não atribui revisão humana, não transforma resultados em avaliação oficial e não deve responder por decisões clínicas reais.</p></LegalPage>}
function Footer({go}:{go:(p:Page)=>void}){return <footer><span>Treino ENAMED · protótipo independente</span><div><button onClick={()=>go('about')}>Sobre</button><button onClick={()=>go('privacy')}>Privacidade e LGPD</button><button onClick={()=>go('ai')}>Uso de IA</button></div></footer>}

function HomePage({attempts,go}:{attempts:Attempt[];go:(p:Page)=>void}){const correct=attempts.filter(a=>a.correct).length;return <><header><div><p className="eyebrow">BOA NOITE</p><h1>Pronto para uma sessão curta?</h1><p>Dez minutos de prática deliberada valem mais que uma revisão sem direção.</p></div><div className="streak">○ <b>{attempts.length}</b><small>respostas</small></div></header><section className="hero"><div><span className="pill">MISSÃO DE HOJE</span><h2>Treino rápido</h2><p>4 questões variadas, com confiança e feedback por alternativa.</p><button className="primary" onClick={()=>go('train')}>Começar agora <ChevronRight size={18}/></button></div><Brain size={90}/></section><div className="grid3"><Card title="Precisão" value={attempts.length?`${Math.round(correct/attempts.length*100)}%`:'—'} note={`${correct} de ${attempts.length} respostas`}/><Card title="Revisões" value={String(attempts.filter(a=>!a.correct).length)} note="itens no caderno de erros"/><Card title="Calibração" value={attempts.length?'Em formação':'—'} note="confiança × acerto"/></div><section className="panel"><div className="sectionTitle"><div><p className="eyebrow">CONTINUE POR ONDE IMPORTA</p><h2>Áreas de treino</h2></div><button className="textBtn" onClick={()=>go('train')}>Ver todas</button></div><div className="areas">{['Clínica Médica','Cirurgia','Pediatria','MFC'].map((x,i)=><button key={x} onClick={()=>go('train')}><span>{['CM','CI','PE','MF'][i]}</span><div><b>{x}</b><small>{i+1} questões disponíveis</small></div><ChevronRight size={17}/></button>)}</div></section></>}
function Card({title,value,note}:{title:string;value:string;note:string}){return <div className="metric"><small>{title}</small><b>{value}</b><p>{note}</p></div>}

function Training({add,questions,loading,error,persistenceError}:{add:(a:Attempt)=>Promise<void>;questions:Question[];loading:boolean;error:string;persistenceError:string}){const [idx,setIdx]=useState(0);const [answer,setAnswer]=useState<Alternative['id']|'UNCERTAIN'|null>(null);const [confidence,setConfidence]=useState<1|2|3>(2);const [done,setDone]=useState(false);const [startedAt,setStartedAt]=useState(()=>Date.now());if(loading)return <Empty text="Carregando questões revisadas…"/>;if(error)return <Empty text={`Não foi possível carregar o banco: ${error}`}/>;if(!questions.length)return <Empty text="Ainda não há questões com revisão humana liberadas para treino."/>;const q=questions[idx%questions.length];const submit=()=>{if(!answer)return;void add({questionId:q.id,questionVersion:q.version,answer,confidence,correct:answer===q.correct,responseTimeMs:Date.now()-startedAt,at:new Date().toISOString()});setDone(true)};const next=()=>{setIdx((idx+1)%questions.length);setAnswer(null);setDone(false);setConfidence(2);setStartedAt(Date.now())};return <><header><div><p className="eyebrow">TREINO RÁPIDO · {idx+1}/{questions.length}</p><h1>{q.area}</h1><p>{q.topic}</p></div><div className={`status ${q.status}`}>{labels[q.status]}</div></header><section className="question">{persistenceError&&<p className="reviewError">{persistenceError}</p>}<p className="stem">{q.stem}</p><div className="alternatives">{q.alternatives.map(a=><button disabled={done} className={`${answer===a.id?'selected':''} ${done&&a.id===q.correct?'correct':''} ${done&&answer===a.id&&a.id!==q.correct?'wrong':''}`} onClick={()=>setAnswer(a.id)} key={a.id}><span>{a.id}</span><div>{a.text}{done&&<small>{a.rationale}</small>}</div></button>)}<button disabled={done} className={answer==='UNCERTAIN'?'selected':''} onClick={()=>setAnswer('UNCERTAIN')}><span>?</span><div>Não tenho certeza</div></button></div>{!done?<div className="submitRow"><div><small>Quão confiante você está?</small><div className="confidence">{([1,2,3] as const).map(c=><button className={confidence===c?'active':''} onClick={()=>setConfidence(c)} key={c}>{['Baixa','Média','Alta'][c-1]}</button>)}</div></div><button className="primary" disabled={!answer} onClick={submit}>Confirmar resposta</button></div>:<div className="feedback"><div><BookOpenCheck/><div><b>{answer===q.correct?'Boa decisão clínica.':'Vamos transformar o erro em revisão.'}</b><p>{q.pearl}</p><small>{q.source}</small></div></div><button className="primary" onClick={next}>Próxima questão <ChevronRight size={18}/></button></div>}</section></>}

function Review({attempts,questions}:{attempts:Attempt[];questions:Question[]}){const wrong=attempts.filter(a=>!a.correct).reverse();return <><header><div><p className="eyebrow">CADERNO DE ERROS</p><h1>Revisar para não repetir</h1><p>Erros e acertos inseguros se transformam em próximas ações.</p></div></header><section className="panel list">{wrong.length?wrong.map((a,i)=>{const q=questions.find(q=>q.id===a.questionId)!;return <div key={i}><span className="areaTag">{q.area}</span><div><b>{q.topic}</b><p>{q.stem}</p></div><button>Revisar</button></div>}):<Empty text="Seu caderno ainda está vazio. Faça um treino para começar."/>}</section></>}
function Progress({attempts}:{attempts:Attempt[]}){const matrix=useMemo(()=>[1,2,3].map(conf=>({conf,total:attempts.filter(a=>a.confidence===conf).length,ok:attempts.filter(a=>a.confidence===conf&&a.correct).length})),[attempts]);return <><header><div><p className="eyebrow">PROGRESSO</p><h1>Mais do que porcentagem</h1><p>Veja se sua confiança acompanha o seu conhecimento.</p></div></header><div className="grid3">{matrix.map(x=><Card key={x.conf} title={`Confiança ${['baixa','média','alta'][x.conf-1]}`} value={x.total?`${Math.round(x.ok/x.total*100)}%`:'—'} note={`${x.ok}/${x.total} acertos`}/>)}</div><section className="panel"><h2>Como interpretar</h2><div className="insight"><Sparkles/><p><b>Erro com alta confiança</b> merece prioridade: pode representar um modelo mental incorreto, não apenas esquecimento.</p></div></section></>}
function Empty({text}:{text:string}){return <div className="empty"><Library size={42}/><p>{text}</p></div>}
