import { useMemo, useState } from 'react';
import { BookOpenCheck, Brain, ChartNoAxesColumnIncreasing, ChevronRight, CircleAlert, FlaskConical, Home, Library, RotateCcw, Sparkles } from 'lucide-react';
import { questions } from './data';
import type { Alternative, Attempt, Question } from './types';

type Page='home'|'train'|'review'|'progress'|'studio';
const labels={especialista:'Revisada por especialista',verificada_ia:'Verificada automaticamente',experimental:'Experimental'} as const;
const nav=[['home','Início',Home],['train','Treinar',Brain],['review','Revisar',RotateCcw],['progress','Progresso',ChartNoAxesColumnIncreasing],['studio','Estúdio',FlaskConical]] as const;

function useAttempts(){
 const [attempts,setAttempts]=useState<Attempt[]>(()=>JSON.parse(localStorage.getItem('treino-attempts')||'[]'));
 const add=(a:Attempt)=>setAttempts(v=>{const n=[...v,a];localStorage.setItem('treino-attempts',JSON.stringify(n));return n});
 return {attempts,add};
}

export function App(){
 const [page,setPage]=useState<Page>('home'); const {attempts,add}=useAttempts();
 return <div className="shell"><aside><div className="brand"><span>T</span><div>Treino <b>ENAMED</b><small>protótipo independente</small></div></div><nav>{nav.map(([id,label,Icon])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><Icon size={19}/>{label}</button>)}</nav><div className="independent"><CircleAlert size={18}/><span>Ferramenta independente, sem vínculo oficial com o INEP, MEC ou instituição de ensino.</span></div></aside><main>{page==='home'&&<HomePage attempts={attempts} go={setPage}/>} {page==='train'&&<Training add={add}/>} {page==='review'&&<Review attempts={attempts}/>} {page==='progress'&&<Progress attempts={attempts}/>} {page==='studio'&&<Studio/>}</main></div>
}

function HomePage({attempts,go}:{attempts:Attempt[];go:(p:Page)=>void}){const correct=attempts.filter(a=>a.correct).length;return <><header><div><p className="eyebrow">BOA NOITE</p><h1>Pronto para uma sessão curta?</h1><p>Dez minutos de prática deliberada valem mais que uma revisão sem direção.</p></div><div className="streak">○ <b>{attempts.length}</b><small>respostas</small></div></header><section className="hero"><div><span className="pill">MISSÃO DE HOJE</span><h2>Treino rápido</h2><p>4 questões variadas, com confiança e feedback por alternativa.</p><button className="primary" onClick={()=>go('train')}>Começar agora <ChevronRight size={18}/></button></div><Brain size={90}/></section><div className="grid3"><Card title="Precisão" value={attempts.length?`${Math.round(correct/attempts.length*100)}%`:'—'} note={`${correct} de ${attempts.length} respostas`}/><Card title="Revisões" value={String(attempts.filter(a=>!a.correct).length)} note="itens no caderno de erros"/><Card title="Calibração" value={attempts.length?'Em formação':'—'} note="confiança × acerto"/></div><section className="panel"><div className="sectionTitle"><div><p className="eyebrow">CONTINUE POR ONDE IMPORTA</p><h2>Áreas de treino</h2></div><button className="textBtn" onClick={()=>go('train')}>Ver todas</button></div><div className="areas">{['Clínica Médica','Cirurgia','Pediatria','MFC'].map((x,i)=><button key={x} onClick={()=>go('train')}><span>{['CM','CI','PE','MF'][i]}</span><div><b>{x}</b><small>{i+1} questões disponíveis</small></div><ChevronRight size={17}/></button>)}</div></section></>}
function Card({title,value,note}:{title:string;value:string;note:string}){return <div className="metric"><small>{title}</small><b>{value}</b><p>{note}</p></div>}

function Training({add}:{add:(a:Attempt)=>void}){const [idx,setIdx]=useState(0);const [answer,setAnswer]=useState<Alternative['id']|'UNCERTAIN'|null>(null);const [confidence,setConfidence]=useState<1|2|3>(2);const [done,setDone]=useState(false);const q=questions[idx];const submit=()=>{if(!answer)return;add({questionId:q.id,answer,confidence,correct:answer===q.correct,at:new Date().toISOString()});setDone(true)};const next=()=>{setIdx((idx+1)%questions.length);setAnswer(null);setDone(false);setConfidence(2)};return <><header><div><p className="eyebrow">TREINO RÁPIDO · {idx+1}/{questions.length}</p><h1>{q.area}</h1><p>{q.topic}</p></div><div className={`status ${q.status}`}>{labels[q.status]}</div></header><section className="question"><p className="stem">{q.stem}</p><div className="alternatives">{q.alternatives.map(a=><button disabled={done} className={`${answer===a.id?'selected':''} ${done&&a.id===q.correct?'correct':''} ${done&&answer===a.id&&a.id!==q.correct?'wrong':''}`} onClick={()=>setAnswer(a.id)} key={a.id}><span>{a.id}</span><div>{a.text}{done&&<small>{a.rationale}</small>}</div></button>)}<button disabled={done} className={answer==='UNCERTAIN'?'selected':''} onClick={()=>setAnswer('UNCERTAIN')}><span>?</span><div>Não tenho certeza</div></button></div>{!done?<div className="submitRow"><div><small>Quão confiante você está?</small><div className="confidence">{([1,2,3] as const).map(c=><button className={confidence===c?'active':''} onClick={()=>setConfidence(c)} key={c}>{['Baixa','Média','Alta'][c-1]}</button>)}</div></div><button className="primary" disabled={!answer} onClick={submit}>Confirmar resposta</button></div>:<div className="feedback"><div><BookOpenCheck/><div><b>{answer===q.correct?'Boa decisão clínica.':'Vamos transformar o erro em revisão.'}</b><p>{q.pearl}</p><small>{q.source}</small></div></div><button className="primary" onClick={next}>Próxima questão <ChevronRight size={18}/></button></div>}</section></>}

function Review({attempts}:{attempts:Attempt[]}){const wrong=attempts.filter(a=>!a.correct).reverse();return <><header><div><p className="eyebrow">CADERNO DE ERROS</p><h1>Revisar para não repetir</h1><p>Erros e acertos inseguros se transformam em próximas ações.</p></div></header><section className="panel list">{wrong.length?wrong.map((a,i)=>{const q=questions.find(q=>q.id===a.questionId)!;return <div key={i}><span className="areaTag">{q.area}</span><div><b>{q.topic}</b><p>{q.stem}</p></div><button>Revisar</button></div>}):<Empty text="Seu caderno ainda está vazio. Faça um treino para começar."/>}</section></>}
function Progress({attempts}:{attempts:Attempt[]}){const matrix=useMemo(()=>[1,2,3].map(conf=>({conf,total:attempts.filter(a=>a.confidence===conf).length,ok:attempts.filter(a=>a.confidence===conf&&a.correct).length})),[attempts]);return <><header><div><p className="eyebrow">PROGRESSO</p><h1>Mais do que porcentagem</h1><p>Veja se sua confiança acompanha o seu conhecimento.</p></div></header><div className="grid3">{matrix.map(x=><Card key={x.conf} title={`Confiança ${['baixa','média','alta'][x.conf-1]}`} value={x.total?`${Math.round(x.ok/x.total*100)}%`:'—'} note={`${x.ok}/${x.total} acertos`}/>)}</div><section className="panel"><h2>Como interpretar</h2><div className="insight"><Sparkles/><p><b>Erro com alta confiança</b> merece prioridade: pode representar um modelo mental incorreto, não apenas esquecimento.</p></div></section></>}
function Studio(){return <><header><div><p className="eyebrow">ESTÚDIO DE QUESTÕES</p><h1>Produção com verificação rastreável</h1><p>Geração, crítica independente, reparo e publicação experimental.</p></div><button className="primary"><Sparkles size={17}/> Nova questão</button></header><div className="grid3"><Card title="Publicadas" value="4" note="1 revisada por especialista"/><Card title="Em verificação" value="0" note="fila automatizada"/><Card title="Custo hoje" value="$ 0,00" note="orçamento configurável"/></div><section className="panel"><div className="sectionTitle"><div><p className="eyebrow">PIPELINE</p><h2>Loop de verificação</h2></div></div><div className="pipeline">{['Blueprint','Gerar','Validar estrutura','Avaliar às cegas','Verificar fonte','Publicar'].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b><small>{i===0?'Código':i===2?'Código':'Claude/Gemini'}</small></div>)}</div><div className="notice"><CircleAlert/><p>As chaves dos provedores serão usadas apenas no servidor. Questões sem revisão humana serão identificadas como “verificadas automaticamente” ou “experimentais”.</p></div></section><section className="panel"><h2>Banco atual</h2><div className="table">{questions.map(q=><div key={q.id}><span className="areaTag">{q.area}</span><b>{q.topic}</b><span className={`status ${q.status}`}>{labels[q.status]}</span><button>Editar</button></div>)}</div></section></>}
function Empty({text}:{text:string}){return <div className="empty"><Library size={42}/><p>{text}</p></div>}
