import { useEffect, useState } from 'react';
import { CheckCircle2, CircleAlert, FileSearch, LoaderCircle, XCircle } from 'lucide-react';
import { supabase, useAuth } from './auth';

type QueueItem={id:string;status:string;current_version:number;question_versions:{body:{area?:string;topic?:string;stem?:string;source?:string};provenance?:unknown}[]};

export function EditorialQueue(){
 const {user}=useAuth();const [items,setItems]=useState<QueueItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=async()=>{if(!supabase||user?.mode==='demo'){setLoading(false);return}setLoading(true);const {data,error}=await supabase.from('questions').select('id,status,current_version,question_versions(body,provenance)').in('status',['auto_verified','experimental','blocked']).order('created_at',{ascending:false});if(error)setError(error.message);else setItems((data||[]) as QueueItem[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 return <><header><div><p className="eyebrow">FILA EDITORIAL</p><h1>Publicar exige evidência, não confiança na IA.</h1><p>A aprovação humana requer revisão clínica, conferência da fonte primária e justificativa auditável.</p></div></header>{user?.mode==='demo'?<section className="panel editorialEmpty"><FileSearch/><h2>Fila demonstrativa</h2><p>Conecte o Supabase e atribua papel de revisor ou administrador para analisar itens reais. Nenhuma aprovação é simulada localmente.</p></section>:loading?<section className="panel editorialEmpty"><LoaderCircle className="spin"/><p>Carregando fila…</p></section>:error?<section className="panel editorialError"><CircleAlert/><p>{error}</p></section>:items.length?<div className="editorialList">{items.map(item=><ReviewCard key={item.id} item={item} done={load}/>)}</div>:<section className="panel editorialEmpty"><CheckCircle2/><h2>Fila vazia</h2><p>Não há questões aguardando decisão editorial.</p></section>}</>
}

function ReviewCard({item,done}:{item:QueueItem;done:()=>Promise<void>}){const body=item.question_versions.find(v=>true)?.body||{};const [clinical,setClinical]=useState(false);const [source,setSource]=useState(false);const [notes,setNotes]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const decide=async(decision:'approve'|'block')=>{if(!supabase)return;setBusy(true);setError('');const {error}=await supabase.rpc('review_question',{p_question_id:item.id,p_decision:decision,p_clinical_reviewed:clinical,p_source_verified:source,p_notes:notes});if(error)setError(error.message);else await done();setBusy(false)};return <article className="panel reviewCard"><div className="reviewMeta"><span>{body.area||'Área não informada'}</span><b>{body.topic||'Tema não informado'}</b><small>{item.status} · versão {item.current_version}</small></div><p className="reviewStem">{body.stem}</p><div className="sourceBox"><b>Fonte declarada pelo gerador</b><p>{body.source||'Não informada'}</p></div><label className="reviewCheck"><input type="checkbox" checked={clinical} onChange={e=>setClinical(e.target.checked)}/>Revisei mérito clínico, gabarito, distratores e segurança.</label><label className="reviewCheck"><input type="checkbox" checked={source} onChange={e=>setSource(e.target.checked)}/>Localizei e conferi a afirmação em fonte documental adequada.</label><label className="reviewNotes">Justificativa da decisão<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Registre achados, fonte consultada e eventuais ressalvas…"/></label>{error&&<p className="reviewError">{error}</p>}<div className="reviewActions"><button disabled={busy||notes.trim().length<20} onClick={()=>decide('block')}><XCircle size={17}/> Bloquear</button><button className="primary" disabled={busy||!clinical||!source||notes.trim().length<20} onClick={()=>decide('approve')}><CheckCircle2 size={17}/> Aprovar após revisão</button></div></article>}
