import React from 'react';
import ReactDOM from 'react-dom/client';
import { App } from './App';
import { AuthProvider } from './auth';
import './styles.css';
import './legal.css';
import './auth.css';
import './studio.css';
import './persistence.css';
import './editorial.css';
import './admin-dashboard.css';
import './catalog.css';
import './bank-factory.css';
import './import-notice.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><AuthProvider><App/></AuthProvider></React.StrictMode>);
